<a href="https://colab.research.google.com/github/whiphish/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

## Assignment 3 : Matrices

Matrices are group of numbers that are arranged by rows and columns in a rectangular manner. According to Aakash+byju's (n.d.), matrices are characterized by m number of rows and n number of columns and are confined by brackets "[ ]" and parentheses "( )".

### Objectives
At the end of this activity you will be able to:
1. Know about matrices and their connection to linear equations.
2. Understand basic matrix operations.
3. Program and translate matrix equations and operations using Python.

##Discussion


In [ ]:
#fcns needed in order for several symbols and operations to be used

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices


In this part, the students learned how to code linear equations into in Python Programming Language. 

$$
A = \left\{
    \begin{array}\
        2x + 5y \\ 
        7x - 35y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        10x-y+6z \\ 
        4x -y -9z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w-x-2y+z \\
      2w-x+3y-2z
    \end{array}
\right. \\
$$

The student learned to convert linear equation into its matrix form.

$$
A=\begin{bmatrix} 5 & 7 \\ 3 & -15\end{bmatrix} \\
B=\begin{bmatrix} 70 & 69 & 30 \\ 2 & -5 & -10 \\ -12 & 43 & 21\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}\\
$$

#### Declaring Matrices

Just like our previous laboratory activity, we'll represent a system of linear equations as a matrix. It is important for us to declare matrices correctly in order for us to make the computer execute the necessary and appropriate operations needed to solve a certain task or problem. Given below is matrix A. Each matrix is composed of rows and columns as its element. In here, the elements are being denoted or characterized by a(i,j); i being its row number and j being its column number.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
#Defining Matrix
#used to perform operations such as stating the given matrix, its shape, and its dimension
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
#Example on how to define matrices
A = np.array([
    [10, 25],
    [31, 12]
])
describe_mat(A)

Matrix:
[[10 25]
 [31 12]]

Shape:	(2, 2)
Rank:	2



In [ ]:
#Another Example of defining matrices
B = np.array([
    [12,13,34],
    [25,21,42]
])
describe_mat(B)

Matrix:
[[12 13 34]
 [25 21 42]]

Shape:	(2, 3)
Rank:	2



In [ ]:
#Another Example of defining matrices
C = np.array([
    [81, 22],
    [55, 43],
    [12, 10]
])
describe_mat(C)

Matrix:
[[81 22]
 [55 43]
 [12 10]]

Shape:	(3, 2)
Rank:	2



In [ ]:
D = np.array([10,20,30,40])
describe_mat(D)

Matrix:
[10 20 30 40]

Shape:	(4,)
Rank:	1



#### Categorizing Matrices

There are several ways of classifying matrices. One could be according to their shape and another is according to their element values. Matrices that are classified according to their shape are grouped into several kinds namely Row and Column Matrices and Square Matrices. Matrices that are classified according to their element values are grouped as follows: Null Matrix, Zero Matrix, Ones Matrix, Diagonal Matrix, Identity Matrix, Upper Triangular Matrix, and Lower Triangular Matrix.





##### According to shape

Matrices can be classified according to their shape. We can determine the shape of a matrix by identifying its number of rows and columns. In this section, the students indicated that matrices can be grouped into a row and column matrices, and square matrices. Here, we can identify the differences between the two kinds of matrices.


###### Row and Column Matrices

Row Matrices are matrices that only have one row of elements. Column Matrices are matrices that only have one column of elements. The students should be careful in encoding the number of brackets in order for them to produce a proper output.

In [ ]:
##### Declaring a Row Matrix

row1D = np.array([
    15, 30, 21, -42
]) ## this is a 1-D Matrix with a shape of (4,), it's not really considered as a row matrix.
row2D = np.array([
    [10,21,36,-45]
]) ## this is a 2-D Matrix with a shape of (1,4)
describe_mat(row1D)
describe_mat(row2D)

Matrix:
[ 15  30  21 -42]

Shape:	(4,)
Rank:	1

Matrix:
[[ 10  21  36 -45]]

Shape:	(1, 4)
Rank:	2



In [ ]:
##### Declaring a Column Matrix

col1 = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col1)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



###### Square Matrices

Square Matrices are matrices whose number of rows and columns are equal to one another. 

In [ ]:
##fcn that define describe_mat(matrix)
##used to declare the matrix, its shape, rank, dimensions, and tell if it is a square matrix or not
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
#declaring matrices and their output using describe_mat()
square = np.array([
    [15,24,51],
    [33,36,81],
    [69,12,21]
])

notsquare = np.array([
    [12,21,57],
    [33,39,84]
])
describe_mat(square)
describe_mat(notsquare)

Matrix:
[[15 24 51]
 [33 36 81]
 [69 12 21]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[12 21 57]
 [33 39 84]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##### According to element values

An element is a number or character inside a matrix. In this section, the students learned about the classification of matrices according to its element values. Matrices are grouped into Null Matrix, Zero Matrix, Ones Matrix, Diagonal Matrix, Identity Matrix, Upper Triangular Matrix, and Lower Triangular Matrix.

###### Null Matrix

Null Matrices are matrices who have no element or the whole matrix is empty.

In [ ]:
#defining describe_mat(matrix)
#used to declare the matrix, its shape, rank, dimension, tell if it is a square matrix or not and determining whether the said matrix is null or not.
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
#Example of null matrix and usage of defined fcn
null = np.array([])
describe_mat(null)

Matrix is Null


###### Zero Matrix

Zero Matrix is a matrix whose elements are zeroes. From its row and column, all elements are zeroes. 

In [ ]:
#Zero matrices

zerorow = np.zeros((1,3))
zerosquare = np.zeros((4,4))
zerorectangle = np.zeros((6,5))

print(f'Zero Row Matrix: \n{zerorow}')
print(f'Zero Square Matrix: \n{zerosquare}')
print(f'Zero Rectangular Matrix: \n{zerorectangle}')

Zero Row Matrix: 
[[0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###### Ones Matrix

Compared to Zero Matrix, the one Matrix is composed of number one from its rows to its columns. 

In [ ]:
#Ones Matrix

onesrow = np.ones((1,3))
onessqr = np.ones((4,4))
onesrct = np.ones((6,5))

print(f'Ones Row Matrix: \n{onesrow}')
print(f'Ones Square Matrix: \n{onessqr}')
print(f'Ones Rectangular Matrix: \n{onesrct}')

Ones Row Matrix: 
[[1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###### Diagonal Matrix

Diagonal Matrix is a matrix who has element values that may or may not be equal to zero that is patterned diagonally. Aside from these element values, all other elements are equal to zero.

In [ ]:
#Diagonal Matrix
np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#Other way to declare a diagonal matrix
diag = np.diag([3,6,9,12,15,18,21])
diag

array([[ 3,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0, 15,  0,  0],
       [ 0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0, 21]])

###### Identity Matrix

Identity Matrix is a matrix that has elements equal to one that is patterned diagonally and all other elements are equal to zero.

In [ ]:
#Identity Matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#Other Way to Declare an Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### Upper Triangular Matrix

Upper Triangular Matrix is a matrix wherein there are increase in the number of elements as the reader goes to the right and downward.

In [ ]:
#Upper Triangular Matrix
np.array([
    [10,20,30,40],
    [0,30,10,-10],
    [0,0,50,20],
    [0,0,0,20]
])

array([[ 10,  20,  30,  40],
       [  0,  30,  10, -10],
       [  0,   0,  50,  20],
       [  0,   0,   0,  20]])

In [ ]:
#Other Way to Declare Upper Triangular Matrix
E = np.array([
              [21, -33, 42, -51, 60],
              [21, -33, 42, -51, 60],
              [21, -33, 42, -51, 60],
              [21, -33, 42, -51, 60],
              [21, -33, 42, -51, 60],
])
np.triu(E)

array([[ 21, -33,  42, -51,  60],
       [  0, -33,  42, -51,  60],
       [  0,   0,  42, -51,  60],
       [  0,   0,   0, -51,  60],
       [  0,   0,   0,   0,  60]])

###### Lower Triangular Matrix

Lower Triangular Matrix is a matrix wherein there are decrease in the number of elements as the reader goes to the right and downward.

In [ ]:
#Lower Triangular Matrix
np.array([
    [12,0,0,0],
    [63,3,0,0],
    [72,63,51,0],
    [12,51,21,21]
])

array([[12,  0,  0,  0],
       [63,  3,  0,  0],
       [72, 63, 51,  0],
       [12, 51, 21, 21]])

In [ ]:
#Other Way to Declare a Lower Triangular Matrix
np.tril(E)

array([[ 21,   0,   0,   0,   0],
       [ 21, -33,   0,   0,   0],
       [ 21, -33,  42,   0,   0],
       [ 21, -33,  42, -51,   0],
       [ 21, -33,  42, -51,  60]])

## Practice

In this section, the students answered practice problems regarding matrices and how to encode it in its markdown and LaTeX markdown form.

1.Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

ANSWER:

$$
\theta =\begin{bmatrix} 5 & 3 &-1 \end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}
\right.
$$


ANSWER:

$$
A=\begin{bmatrix} 1 & 2 & 3\\ 0 & 4 & -1\\ 0 & 0 & 10\end{bmatrix}\\
$$


The matrix A has spots where the values of $x_{1}$ and $x_{2}$ are equal to zero because they are not included in the linear equation. This is an example of upper triangular matrix wherein there are increase in the number of elements as the reader goes to the right and downward.

3.Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

ANSWER:

Markdown
$$
G = \left\{\begin{array}
1x + 7y + 8z\\
2x + 2y + 2z\\
4x + 6y + 7z
\end{array}
\right.
$$

LaTeX markdown

$$
G=\begin{bmatrix} 1 & 7 & 8\\ 2 & 2 & 2\\ 4 & 6 & 7\end{bmatrix} \\
$$

4.Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

ANSWER:

LaTeX markdown

$$
H=\begin{bmatrix} 1 & 0 & 0\\ 2 & 2 & 0\\ 4 & 6 & 7\end{bmatrix} \\
$$

System of Linear combinations
$$
H = \left\{
    \begin{array}\
        x \\ 
        2x + 2y \\
        4x + 6y + 7z\
    \end{array}
\right. 
$$

## Matrix Algebra

In this section, the students learned to input different arithmetic operations involving matrices.

### Addition

In this part, the students learned to perform addition involving matrices using Python Programming Language.

In [ ]:
#Declaring Matrix I and J and Addition of Matrices
I = np.array([
    [12,21],
    [21,33],
    [42,12]
])
J = np.array([
    [21,24],
    [0,0],
    [15,18]
])
I+J

array([[33, 45],
       [21, 33],
       [57, 30]])

In [ ]:
3+I ###Broadcasting
#3*np.ones(I.shape)+I

array([[15, 24],
       [24, 36],
       [45, 15]])

In [ ]:
#Other Way to perform Addition of Matrices
np.add(I,J)

array([[33, 45],
       [21, 33],
       [57, 30]])

### Subtraction

In this part, the students learned to perform subtraction operation involving matrices using Python Programming Language.

In [ ]:
# Subtraction of Matrices
I-J

array([[-9, -3],
       [21, 33],
       [27, -6]])

In [ ]:
2-I
#2*np.ones(I.shape)-I

array([[-10, -19],
       [-19, -31],
       [-40, -10]])

### Element-wise Multiplication

In this part, the students learned to perform element-wise multiplication operation involving matrices using Python Programming Language.

In [ ]:
#Element-wise Multiplication
I*J
#np.multiply(I,J)

array([[252, 504],
       [  0,   0],
       [630, 216]])

In [ ]:
#Multiplication of a Constant and a Matrix
3*J

array([[63, 72],
       [ 0,  0],
       [45, 54]])

### Element-wise Division

In this part, the students learned to perform element-wise division operation involving matrices using Python Programming Language.

In [ ]:
#Element-wise Division
J/I

array([[1.75      , 1.14285714],
       [0.        , 0.        ],
       [0.35714286, 1.5       ]])

In [ ]:
#Division involving Matrices
omega=10**-2
I/(omega+J)

array([[5.71156592e-01, 8.74635569e-01],
       [2.10000000e+03, 3.30000000e+03],
       [2.79813458e+00, 6.66296502e-01]])

## Activity

In this section, the students was tasked to give an output that involved the learnings about Matrices in Python. 

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
import numpy as np
def mat_desc(matrix):
    square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:{matrix.ndim}\nSquare Matrix:{square}')
    if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
      print(f'Empty Matrix: True')
    else:
      print(f'Empty Matrix: False')
      
    identity = np.identity(matrix.shape[0])
    if(square and (identity == matrix).all()):
      print(f'Identity Matrix: True')
    else:
      print(f'Identity Matrix: False')
       
    ones = np.ones((matrix.shape[0], matrix.shape[1]))
    if((ones == matrix).all()):
      print(f'Ones Matrix: True')
    else:
      print(f'Ones Matrix: False')
    
    zero = np.zeros((matrix.shape[0], matrix.shape[1]))
    if((zero == matrix).all()):
      print(f'Zero Matrix: True \n')
    else:
      print(f'Zero Matrix: False \n')

In [ ]:
## Matrix Declarations
K = np.array([
    [21,15,14],
    [7,21,33],
    [55,56,13]
])

L = np.array([
    [44,21,13,4],
    [12,11,10,8],
    [7,4,8,12],
    [19,21,29,16]
])

M = np.array([
    [15,24,51,69],
    [33,36,81,75],
    [69,12,21,91]
])

N = np.array([
    [12,21,57,10],
    [33,39,84,20],
    [55,62,13,30],
    [1,2,3,40],
    [10,11,12,50]
])

O = np.array([
    [55,72,81,51],
    [11,11,11,11],
    [2,50,71,81],
    [31,35,82,69]
])


In [ ]:
## Test Areas
mat_desc(K)

mat_desc(L)

mat_desc(M)

mat_desc(N)

mat_desc(O)

Matrix:
[[21 15 14]
 [ 7 21 33]
 [55 56 13]]

Shape:	(3, 3)
Rank:2
Square Matrix:True
Empty Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False 

Matrix:
[[44 21 13  4]
 [12 11 10  8]
 [ 7  4  8 12]
 [19 21 29 16]]

Shape:	(4, 4)
Rank:2
Square Matrix:True
Empty Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False 

Matrix:
[[15 24 51 69]
 [33 36 81 75]
 [69 12 21 91]]

Shape:	(3, 4)
Rank:2
Square Matrix:False
Empty Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False 

Matrix:
[[12 21 57 10]
 [33 39 84 20]
 [55 62 13 30]
 [ 1  2  3 40]
 [10 11 12 50]]

Shape:	(5, 4)
Rank:2
Square Matrix:False
Empty Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False 

Matrix:
[[55 72 81 51]
 [11 11 11 11]
 [ 2 50 71 81]
 [31 35 82 69]]

Shape:	(4, 4)
Rank:2
Square Matrix:True
Empty Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False 



### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
import numpy as np
def mat_operations(P, Q):
    print(f'Matrix 1:\n {P} \n')
    print(f'Matrix 2:\n {Q} \n')

    if(P.shape != Q.shape):
        print('The shape of both matrices are not the same. The system could not perform any operation.')
        return

    plus = P + Q
    print(f'Sum of the chosen matrices:\n {plus} \n')

    minus = P - Q
    print(f'Difference of the chosen matrices: \n {minus} \n')

    matpro = np.multiply(P, Q)
    print(f'Element-wise multiplication of the chosen matrices:\n {matpro}\n')

    matdiv = np.divide(P, Q)
    print(f'Element-wise division of the chosen matrices:\n {matdiv}\n')

In [ ]:
## Matrix Declarations
P = np.array([[13, 40, 30], 
              [30, 10, 40], 
              [50, 60, 12]])
Q = np.array([[12, 21, 42], 
              [21, 30, 42], 
              [42, 51, 60]])
R = np.array([[15, 24, 45], 
              [27, 30, 42], 
              [45, 54, 63]])
S = np.array([[18, 50, 60], 
              [10, 15, 20], 
              [10, 20, 18]])
T = np.array([[16, 25, 45], 
              [25, 35, 45], 
              [45, 55, 65]])

In [ ]:
## Test Areas
mat_operations(P, Q)

Matrix 1:
 [[13 40 30]
 [30 10 40]
 [50 60 12]] 

Matrix 2:
 [[12 21 42]
 [21 30 42]
 [42 51 60]] 

Sum of the chosen matrices:
 [[ 25  61  72]
 [ 51  40  82]
 [ 92 111  72]] 

Difference of the chosen matrices: 
 [[  1  19 -12]
 [  9 -20  -2]
 [  8   9 -48]] 

Element-wise multiplication of the chosen matrices:
 [[ 156  840 1260]
 [ 630  300 1680]
 [2100 3060  720]]

Element-wise division of the chosen matrices:
 [[1.08333333 1.9047619  0.71428571]
 [1.42857143 0.33333333 0.95238095]
 [1.19047619 1.17647059 0.2       ]]



## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".

In this laboratory activity, the students learned the basic concepts behind linear equations, markdown, LaTeX markdown, definition and classifications of matrices, and matrix algebra.

Matrices are groups of numbers that are characterized by their rows and columns. Linear Equations can be converted into Matrices and vice-versa. The students also learned how to code linear equations and matrices using Python. 

Classifications of Matrices are also discussed such as classifications according to its shape: row and column matrices, and square matrices. Matrices are also classified by its element values, namely Null Matrix, Zero Matrix, Ones Matrix, Diagonal Matrix, Identity Matrix, Upper Triangular Matrix, and Lower Triangular Matrix.

Just like integers, matrices can also be manipulated by algebraic operations such as addition, subtraction, element-wise multiplication, and element-wise division.

According to Ferrao (2021), Matrices have different applications in many fields of science such as graphics, games, economics and business, animations, physics, encryption, geology, electrical circuits, and others. In our opinion, matrices can solve problems in technology through applying it in the concept of encryption. One of the problems in technology that we are currently facing is the spreading of personal information. We think that through applying matrices in encryption, people, especially students like us, can be free in using the internet knowing that our personal information is safe from being stolen and being used by other people.

Another usage of matrices is in the field of statistics and research, for example in plotting graphs. In this way, matrices can help the technology to point out problems and can give ideas on how to solve it.

Matrix operations can solve problems in technology because they are used to approximate more sophisticated calculations quickly. Originally, they were created to describe systems of linear equations. Computers can multiply matrices to solve systems of linear equations in applications like image processing and genetic research.