<a href="https://colab.research.google.com/github/whiphish/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment5_Gonzales_Ignacio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE/PetE
## Laboratory 4 : Matrix Operations

### Objectives
At the end of this activity, the students will learn the following advanced topics about matrices and vectors:
1. Operations used to solve intermediate equations.
2. Transposition.
3. Dot product or Inner product.
4. Dot product properties.
5. Determinants.
6. Inverse Matrices
7. Application of Dot Product Properties.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 5 & 1 & 2\\10 & -11 & 10 \\ 10 & -13 & 13\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 5 & 10 & 10\\1 & -11 &-13 \\ 2 & 10 & 13\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
#declaration of variables
A = np.array([
              [1,4,5],
              [2,3,6],
              [9,8,7]
])
A

array([[1, 4, 5],
       [2, 3, 6],
       [9, 8, 7]])

In [ ]:
#transpose
AT1 = np.transpose(A)
AT1

array([[1, 2, 9],
       [4, 3, 8],
       [5, 6, 7]])

In [ ]:
#other way to transpose
AT2 = A.T
AT2

array([[1, 2, 9],
       [4, 3, 8],
       [5, 6, 7]])

In [ ]:
#proof of equality for transpose samples
np.array_equiv(AT1, AT2)

True

In [ ]:
#declaration of variable and its shape
B = np.array([
    [12,21,33,45],
    [15,30,12,15],
    [1,2,3,4],
])
B.shape

(3, 4)

In [ ]:
#declaration of transpose and its shape
np.transpose(B).shape

(4, 3)

In [ ]:
#other way to describe shape of transpose
B.T.shape

(4, 3)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
## Try out your code here.
#declaration of variable and its shape
Z=np.array([
    [32,60,96],
    [13,20,13]        
])
Z.shape

(2, 3)

In [ ]:
#declaration of transpose and its shape
np.transpose(Z).shape

(3, 2)

In [ ]:
#other way to describe shape of transpose
Z.T.shape

(3, 2)

In [ ]:
#transpose
ZT = Z.T
ZT

array([[32, 13],
       [60, 20],
       [96, 13]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
#declaration of variables
X = np.array([
    [5,10,25],
    [10,15,25],
    [1,2,3]
])
Y = np.array([
    [-12,20,21],
    [24,27,30],
    [10,20,30]
])

In [ ]:
#declaration of equality of variables
np.array_equiv(X, Y)

False

In [ ]:
#dot product of variables
np.dot(X,Y)

array([[ 430,  870, 1155],
       [ 490, 1105, 1410],
       [  66,  134,  171]])

In [ ]:
#other way to show dot product
X.dot(Y)

array([[ 430,  870, 1155],
       [ 490, 1105, 1410],
       [  66,  134,  171]])

In [ ]:
#other way to show dot product
X @ Y

array([[ 430,  870, 1155],
       [ 490, 1105, 1410],
       [  66,  134,  171]])

In [ ]:
#other way to show dot product
np.matmul(X,Y)

array([[ 430,  870, 1155],
       [ 490, 1105, 1410],
       [  66,  134,  171]])

In [ ]:
#declaration of variables
D = np.array([
    [33,24,21],
    [32,10,35],
    [51,32,21]
])
E = np.array([
    [-20,10,15],
    [22,42,61],
    [71,42,30]
])

In [ ]:
#dot product
D @ E

array([[1359, 2220, 2589],
       [2065, 2210, 2140],
       [1175, 2736, 3347]])

In [ ]:
#other way to show dot product
D.dot(E)

array([[1359, 2220, 2589],
       [2065, 2210, 2140],
       [1175, 2736, 3347]])

In [ ]:
#other way to show dot product
np.matmul(D, E)

array([[1359, 2220, 2589],
       [2065, 2210, 2140],
       [1175, 2736, 3347]])

In [ ]:
#other way to show dot product
np.dot(D, E)

array([[1359, 2220, 2589],
       [2065, 2210, 2140],
       [1175, 2736, 3347]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
#declaration of variables and their shapes
I = np.array([
    [21, 40],
    [15, -21],
    [10, 12]
])
G = np.array([
    [12,15],
    [13,31],
    [-12,-23]
])
N = np.array([
    [20,15,13],
    [10,15,21]
])
print(I.shape)
print(G.shape)
print(N.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
#dot product
I @ N

array([[ 820,  915, 1113],
       [  90,  -90, -246],
       [ 320,  330,  382]])

In [ ]:
#other way to show dot product
G @ N

array([[ 390,  405,  471],
       [ 570,  660,  820],
       [-470, -525, -639]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
#other way to show dot product
I @ G.T

array([[  852,  1513, -1172],
       [ -135,  -456,   303],
       [  300,   502,  -396]])

In [ ]:
#other way to show dot product
G @ I.T

array([[  852,  -135,   300],
       [ 1513,  -456,   502],
       [-1172,   303,  -396]])

In [ ]:
#declaration of variables and their shape
sam1 = np.array([
    [12,21,33,20]
])
sam2 = np.array([
    [11,20,42,-10]
])
print(sam1.shape)
print(sam2.shape)

(1, 4)
(1, 4)


In [ ]:
#transpose dot variable
sam2.T @ sam1

array([[ 132,  231,  363,  220],
       [ 240,  420,  660,  400],
       [ 504,  882, 1386,  840],
       [-120, -210, -330, -200]])

In [ ]:
#variable dot transpose
sam1 @ sam2.T

array([[1738]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
#declaration of variables
Apple = np.array([
    [12,21,15],
    [40,51,12],
    [15,18,21]
])
Bat = np.array([
    [42,15,60],
    [41,10,19],
    [21,14,28]
])
Cat = np.array([
    [21,31,40],
    [10,11,11],
    [11,10,11]
])

In [ ]:
#declaration of identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#dot product of variable and identity matrix (property 5)
Apple.dot(np.eye(3))

array([[12., 21., 15.],
       [40., 51., 12.],
       [15., 18., 21.]])

In [ ]:
#proving property 1
np.array_equal(Apple@Bat, Bat@Apple)

False

In [ ]:
#declaration of variable Eat
Eat = Apple @ (Bat @ Cat)
Eat

array([[ 58209,  74070,  90729],
       [138018, 175821, 215733],
       [ 65109,  82068, 100179]])

In [ ]:
#declaration of variable Fat
Fat = (Apple @ Bat) @ Cat
Fat

array([[ 58209,  74070,  90729],
       [138018, 175821, 215733],
       [ 65109,  82068, 100179]])

In [ ]:
#stating equality of two variables
np.array_equal(Eat, sam1)

False

In [ ]:
#stating equivalence of two variables (property 2)
np.array_equiv(Eat, Fat)

True

In [ ]:
#Property 3
prop31 = Apple @ (Bat+Cat)
prop32 = (Apple@Bat)+(Apple@Cat)
np.array_equiv(prop31, prop32)

True

In [ ]:
#Property 4
prop41 = (Bat+Cat) @ Apple
prop42 = (Bat@Apple)+(Cat@Apple)
np.array_equiv(prop41, prop42)

True

In [ ]:
#Property 6
null_mat3 = np.empty(Apple.shape, dtype=float)
null3 = np.array(null_mat3, dtype=float)
Applenull = (Apple @ null3)
np.array_equiv(Applenull, null3)

False

In [ ]:
#identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#dot product
Apple @ Eat

array([[ 4573521,  5812101,  7121826],
       [10148586, 12914487, 15833691],
       [ 4724748,  5999256,  7347888]])

In [ ]:
#zeroes matrix
Zero = np.zeros(Apple.shape)
Zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#dot product of variable and zero matrix
Apple_dot_Zero = Apple.dot(np.zeros(Apple.shape))
Apple_dot_Zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#stating equality of dot product of variable and zero matrix and, zero matrix
np.array_equal(Apple_dot_Zero,Zero)

True

In [ ]:
#null matrix
null_mat = np.empty(Apple.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(Apple_dot_Zero,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be greatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
#declaration of variable and its determinant
Gamma = np.array([
    [13,40],
    [10,30]
])
np.linalg.det(Gamma)

-10.00000000000001

In [ ]:
#declaration of variable and its determinant
Beta = np.array([
              [12, 51, 21],
              [36, -12 ,-15],
              [30, -21, 18]
])
np.linalg.det(Beta)

-70685.99999999997

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
Highway = np.array([
    [10,51,23,19],
    [10,10,13,10],
    [20,0,0,0],
    [4,1,10,28]
])
np.linalg.det(Highway)

178139.99999999985

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
#declaration of variable and dot product of inverse and variable
Indigo = np.array([
    [12,71],
    [-30, 15]
])

np.array(Indigo @ np.linalg.inv(Indigo), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
#declaration of variables and its inverse
Jacket = np.array([
              [16, 19, 10],
              [14, 12, -11],
              [13, 16, 17]
])
Kangaroo = np.linalg.inv(Jacket)
Kangaroo

array([[-0.79331942,  0.34029228,  0.6868476 ],
       [ 0.7954071 , -0.29645094, -0.65970772],
       [-0.14196242,  0.01878914,  0.15448852]])

In [ ]:
#dot product of variable and its inverse
Jacket @ Kangaroo

array([[ 1.00000000e+00, -3.05311332e-16, -3.88578059e-16],
       [-9.43689571e-16,  1.00000000e+00,  9.15933995e-16],
       [-2.05391260e-15, -6.93889390e-17,  1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
Lamda = np.array([
    [18,15,13,11,0,23,15],
    [0,5,0,1,12,0,0],
    [52,19,0,0,0,0,0],
    [2,1,1,1,1,1,1],
    [0,0,0,1,4,3,2],
    [-4,5,0,0,0,1,-3],
    [-3,-1,2,0,11,0,0],
])
Lamda_inv = np.linalg.inv(Lamda)
np.array(Lamda @ Lamda_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

To validate the whether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
#declaration of variables
squad = np.array([
    [1.25, 1.25, 1.0],
    [1.5, 1.5, 1.0],
    [1.25, 1.25, 1.0]
])
weights = np.array([
    [2.0, 2.0, 3.0]
])
p_grade = squad @ weights.T
p_grade


array([[8.],
       [9.],
       [8.]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
#declaration of variables
mat1 = np.array([
                [3,2,1],
                [2,4,6],
                [5,4,3]
])

mat2 = np.array([
                [2,1,0],
                [22,11,10],
                [2,3,4]
])

mat3 = np.array([
                [1,2,3],
                [5,6,7],
                [13,14,15]
])

iden = np.eye(3)

null_mat2 = np.empty(mat1.shape, dtype=float)
null2 = np.array(null_mat2,dtype=float)


In [ ]:
#property 1
mul1 = mat1@mat2
mul2 = mat2@mat1
np.array_equal(mul1, mul2)

False

In [ ]:
#property 2
dot1 = mat1 @ (mat2 @ mat3)
dot2 = (mat1 @ mat2) @ mat3
np.array_equiv(dot1, dot2)

True

In [ ]:
#property 3
dotadd1 = mat1 @ (mat2+mat3)
dotadd2 = (mat1@mat2)+(mat1@mat3)
np.array_equiv(dotadd1, dotadd2)

True

In [ ]:
#property 4
dotadd3 = (mat2+mat3) @ mat1
dotadd4 = (mat2@mat1)+(mat3@mat1)
np.array_equiv(dotadd3, dotadd4)

True

In [ ]:
#property 5
muliden = mat1@iden
np.array_equiv(muliden, mat1)

True

In [ ]:
#property 6
mulnull2 = (mat1@null2)
np.array_equiv(mulnull2, null2)

True

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. 

In this laboratory activity, the students learned about Matrix Operations in Python; its transpositions, the dot product or inner product has two rules - rule 1: the inner dimensions of the two matrices in question must be the same, and rule 2: dot product has special properties. Determinants and inverse are also tackled in this laboratory activity. The students also had the opportunity to create their own matrices in which the shapes should not be lower than (3,3).